### ISSUE TITLE
How to contribute to the docs?

### ISSUE THREAD

**Issue by devingray** [conedevelopment/bazar#102]
How can I contribute to the documentation? 

I managed to get this set up, but had to read through the code to do so.

**Comment by iamgergo** [comment]
Hi!

So, we are opening the docs in a new repo. It's not integrated yet with the real site, but this week we'll do that as well hopefully. You can open PRs/issues there!

Here is the repo: https://github.com/conedevelopment/bazar-docs

Thanks!
