### ISSUE TITLE
Design and Route Not working

### ISSUE THREAD

**Issue by Vinya007** [conedevelopment/bazar#104]
- Bazar Version: 0.4.4
- Laravel Version: 8.25.0
- PHP Version: 7.4.0
- Database Driver & Version: MariaDB

### Description:
![image](https://user-images.githubusercontent.com/70583545/106750597-0ad2c700-664e-11eb-8ab1-cfff7b599cfb.png)

### Steps To Reproduce:
I have minor design issue on admin and profile, password route is not working for me.

**Comment by iamgergo** [comment]
Hi!

Normally we fixed it in the latest release.

This is the related issue: https://github.com/conedevelopment/bazar/issues/86

Could you update Bazar, remove the symlink in the public/vendor/bazar directory?

Then run bazar:install without seeding. Normally it fixes the missing images.

Thanks!

**Comment by iamgergo** [comment]
The Profile and Password routes: yes you are right! When I did the last refactoring, I forgot to register the Vue components...fixed thanks!
