### ISSUE TITLE
Media Modal has some logic error in product/create page

### ISSUE THREAD

**Issue by curder** [conedevelopment/bazar#113]
- Bazar Version: 0.4.6
- Laravel Version: 8.26.1
- PHP Version: 7.4.13
- Database Driver & Version: sqlite

### Description:

When I click the icon in the editor on the left, the right elements is on it.

When I click "Select Media" on the right, It is OK.

I think it is determined by the different documents where the modal is located.

So I tried to modify the left '.form__body { z-index: 11;}' the left Modal is OK, But the modal box on the right is wrong.

### Steps To Reproduce:

The screenshot like this:

![bug](https://user-images.githubusercontent.com/8327004/106986866-3cab7100-67a7-11eb-8298-1229dd33d191.gif)

### Some Ideas:

1. Change `z-index` value when toggle media modal status.

2. We can use [Portal Vue](https://github.com/LinusBorg/portal-vue) package, and Remove `media-manager` component out left and right side, example: Remove to the `.form` child.

**Comment by iamgergo** [comment]
Fixed here https://github.com/conedevelopment/bazar/commit/41854962eb5cddb38e4561b4707384690dbeb76c
