### ISSUE TITLE
Should we publish public directory from current package to Laravel project?

### ISSUE THREAD

**Issue by curder** [conedevelopment/bazar#115]
- Bazar Version: 0.4.6
- Laravel Version: 8.26.1
- PHP Version: 7.4.13
- Database Driver & Version: sqlite

### Is your feature request related to a problem? Please describe

when I run `php artisan bazar:publish --tag=bazar-assets` command [Publish Assets](https://bazar.conedevelopment.com/docs/installation#publishing-assets), But the 'img/' resources already missing.

![image](https://user-images.githubusercontent.com/8327004/106995152-3de59980-67b9-11eb-9966-ffae8568fb20.png)

### Describe the solution you'd like

1. Publish the `public/img` directory to user Laravel project `public/vendor/bazar/img`, like:
Add a line from [L150 - L153](https://github.com/conedevelopment/bazar/blob/master/src/BazarServiceProvider.php#L151)
  ```
  $this->publishes([
      __DIR__. '/../public/img' => App::basePath() . '/public/vendor/bazar/img',
      __DIR__.'/../resources/js' => App::resourcePath('js/vendor/bazar'),
      __DIR__.'/../resources/sass' => App::resourcePath('sass/vendor/bazar'),
  ], 'bazar-assets');
  ```

2. Publish all `public` directory to user Laravel project `public/vendor/bazar`, And I think that's good because when user run `php artisan bazar:publish --tag=bazar-assets`, They no longer need to execute `npm install && npm run dev` command.
  ```
  $this->publishes([
      __DIR__. '/../public' => App::basePath() . '/public/vendor/bazar',
  ], 'bazar-assets');
  ```

### Why do you think this feature is something we should consider for Bazar?

Because User-friendly.

### Additional context

Thanks again for providing the package.

**Comment by curder** [comment]
I found the source code has a symlink for this,  see [InstallCommand](https://github.com/conedevelopment/bazar/blob/master/src/Console/Commands/InstallCommand.php#L41) 

But I am not sure that it is valid for multiple environments, if the user does not need to compile the front-end resources by himself.

I still think it’s better to publish static resources  from `public/` to the user Laravel project directory `public/vendor/bazar`.

**Comment by iamgergo** [comment]
I'll think this through, but you might be right. 

I chose symlinking because using that, we won't overwrite the assets of the user and also, there is no need to republish the assets every time when Bazar is being updated.

But maybe we can just automate that with a composer script.
