### ISSUE TITLE
Rework the form component

### ISSUE THREAD

**Issue by iamgergo** [conedevelopment/bazar#117]
Since we have inertia, it offers a lot of new possibilities, such as handling the forms differently as before.

Our goal is to keep the front-end simple and clean as well, to do so we might implement the following steps:

- Remove the input wrapper components, keep only those we can't avoid handling as a component like: `Tags`, `Autocomplete`, `Editor`
- Use the `preserveState: true` option for the form
- Cleanup the `Errors` class

We might apply a rewrite in Vue 3, reworking the components and adding front-end tests as well.

**Comment by szepeviktor** [comment]
@iamgergo Typo in title: "from"
