### ISSUE TITLE
Add URL helper

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/bazar#125]
### Is your feature request related to a problem? Please describe

There are two `preg_match('/bazar/', Route::getCurrentRoute()->getName())` in the code base.
None of them are nice.

### Describe the solution you'd like

Add an `isBazarRoute` helper.

### Why do you think this feature is something we should consider for Bazar?

Looks professional.

**Comment by iamgergo** [comment]
Maybe a URL macro?

**Comment by szepeviktor** [comment]
I do not speak Greek :)

**Comment by iamgergo** [comment]
Well, then let's keep it as is for now.
