### ISSUE TITLE
Auth error after install and login

### ISSUE THREAD

**Issue by cheello** [conedevelopment/bazar#134]
- Bazar Version: 0.6.0
- Laravel Version: 8.3.0
- PHP Version: 7.4.16
- Database Driver & Version: MySQL 5.7.23

### Description:
Auth error bazar panel after login in app - `'manage-bazar'`

```
Bazar\BazarServiceProvider::Bazar\{closure}
vendor/conedevelopment/bazar/src/BazarServiceProvider.php:226
```

```
    protected function registerAuth(): void

    {

        Gate::define('manage-bazar', static function (Contracts\Models\User $user): bool {

            return $user->isAdmin();

        });

    }
```

### Steps To Reproduce:
install laravel, bazar, (breeze, jetstream, laravel ui), login in app (admin@bazar.test).

**Comment by iamgergo** [comment]
Thanks for the report!

Have you extended your default `App\Models\User` model with `Bazar\Models\User`?

Docs: https://bazar.conedevelopment.com/docs/installation#extending-the-user-model

**Comment by cheello** [comment]
My bad, I didn't take the last step.
Thank you!
