### ISSUE TITLE
Database fields not configured for Uuid's

### ISSUE THREAD

**Issue by rowanfuchs** [conedevelopment/bazar#140]
- Bazar Version: 0.7.0
- Laravel Version: 8.37.0
- PHP Version: 8.0
- Database Driver & Version: mariadb 10.5

### Description:
database id fields are not configured for Uuid's 

> SQLSTATE[01000]: Warning: 1265 Data truncated for column 'shippable_id' at row 1 (SQL: insert into `bazar_shippings` (`tax`, `cost`, `driver`, `shippable_id`, `shippable_type`, `updated_at`, `created_at`) values (0, 0, local-pickup, 38c3b5d1-1135-4c93-8fc2-e5227ef0ed05, Bazar\Models\Cart, 2021-04-16 11:38:38, 2021-04-16 11:38:38))

fixed by setting the field to the char(36)
but is followed by 

> SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'd7df5adb-a383-4fe1-bcd8-53e17b90aa69' for column `dsp`.`bazar_shippings`.`shippable_id` at row 1 (SQL: insert into `bazar_shippings` (`tax`, `cost`, `driver`, `shippable_id`, `shippable_type`, `updated_at`, `created_at`) values (0, 0, local-pickup, d7df5adb-a383-4fe1-bcd8-53e17b90aa69, Bazar\Models\Cart, 2021-04-16 11:50:11, 2021-04-16 11:50:11))

and is also fixed by setting the field to the char(36)

**Comment by szepeviktor** [comment]
That may be true.

https://github.com/conedevelopment/bazar/blob/master/database/migrations/2020_01_01_001000_create_bazar_shippings_table.php#L18

**Comment by szepeviktor** [comment]
How come tests do not fail?

https://github.com/conedevelopment/bazar/blob/788d279c19e3a9bff5921e81601b789f3dba7965/tests/Unit/ShippingTest.php#L37

**Comment by szepeviktor** [comment]
CI runs on sqlite.

https://github.com/conedevelopment/bazar/blob/4cca0f9bf9e1193c6ee637601a6b16c14e143c95/phpunit.xml.dist#L31

**Comment by iamgergo** [comment]
Hi @rowanfuchs,

Yes, you're right, when I changed the `Cart` model's ID, I forgot to update the `Shipping` foreign ID type.

I just released v0.7.1, where normally this is fixed.

Thanks!
