### ISSUE TITLE
Parent category and children

### ISSUE THREAD

**Issue by rowanfuchs** [conedevelopment/bazar#144]
Currently it's only possible to have one level of categories, however by adding a `parent_id` and the following relations a multidimensional category structure is created.  The admin view needs to be adjusted to show a tree structure and dropdown's containing categories can be added to the create/update views

```
/**
 * @return \Illuminate\Database\Eloquent\Relations\HasMany
 */
public function children(): \Illuminate\Database\Eloquent\Relations\HasMany
{
    return $this->hasMany(self::class, 'parent_id');
}

/**
 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
 */
public function parent(): \Illuminate\Database\Eloquent\Relations\BelongsTo
{
    return $this->belongsTo(self::class, 'parent_id');
}
```

This is a small change which provides a beneficial feature. If this is a feature which is considered an addition I can provide an initial pull request with the required changes.

**Comment by iamgergo** [comment]
I was thinking about implementing this before, but then I decided to keep it as simple as possible at the moment.

For you, what would be the main advantage of having this?

**Comment by rowanfuchs** [comment]
I agree that the simplicity of bazar is it's strength, it is the main reason I chose for this framework in my current project. 

Product categorization would improve performance on larger product catalogs, it would also increase landing pages which affect the SEO ranking. They say the user experience is also positively affected by categorization but this is also depended on the multi level categorization itself. 

In my case I want to sell board games, which can be categorized as card games, strategy games, brain games. I was also thinking of misusing the properties/attributes of a product but this isn't a proper use of attributes.

Maybe adding product features would also resolve the above mentioned case. It wouldn't create extra category landing pages, but it would help a user to filter through a larger catalog.

**Comment by iamgergo** [comment]
Sorry for the late response.

So, I think at this phase, when we are before v1.0, and the API, methods and interfaces are still changing quite much, I would rather focus on stabilizing those at the first place.

However, I think you can easily extend the category model, adding a new column to the migration and even overriding the vue components, where you need to.

I think later I'm open to adding this feature as a default one, but not before v1.0.

Anyway, thanks for the patience and the idea!

**Comment by dcbndev** [comment]
Looking forward for this as well, after releasing the stable version.
