### ISSUE TITLE
UserFactory uses Bazar\Model\Users

### ISSUE THREAD

**Issue by ven7ura** [conedevelopment/bazar#150]
- Bazar Version: 0.7.4
- Laravel Version: 8.40.0
- PHP Version: 8.0.5

### Description:
When doing tests, any custom methods on the Users model (in my case fresh installation for Laravel Jetstream) does not register. I know the recommended auth scaffolding is Laravel Breeze, just testing Jetstream with Bazar.
### Steps To Reproduce:
Fresh install of Laravel
Install Laravel Jetstream
Run tests
 `BadMethodCallException: Call to undefined method Bazar\Models\User::deleteProfilePhoto()`

You can fix this by changing `Bazar\Database\Factories\UserFactory`

From
`use Bazar\Models\User;`
To
`use App\Models\User;`

**Comment by iamgergo** [comment]
Hi,

Yes, you are right. I added a dynamic check, it should be fine, but for the long term, we might find out a better solution.

Please upgrade to v0.7.5.

Thanks!
