### ISSUE TITLE
cart to order and return on cancellation process

### ISSUE THREAD

**Issue by rowanfuchs** [conedevelopment/bazar#159]
I'm not sure if I missed it but as far as I see a mid-order cancellation process isn't supported yet. There is a moment where you can create an order which goes perfectly. But what if the payment because of some reason fails after the creation. Within my payment provider the user can cancel or simply return of the page. On that moment a reinitialization of the cart is required so that customers can adjust or extend their cart. 

What process do you use to do so? or is this something of which you are planning to implement?

**Comment by iamgergo** [comment]
I'm currently working on a payment gateway for [QuickPay](https://quickpay.net/), and I had the same questions/issues, but I could solve that quite nicely.

But you are right we are not providing any good example for that in the docs, for now, so we need to improve that as well.

Soon, I'll publish the repository and I can show a concrete example of how to handle these scenarios. I think next week it will be ready, I'll ping you.

Thanks!

**Comment by darkshifty** [comment]
Thank you very much, don't feel rushed. Great work so far!
