### ISSUE TITLE
Add default/favorite product variant

### ISSUE THREAD

**Issue by ven7ura** [conedevelopment/bazar#161]
- Bazar version: 0.8.2
- Laravel version: 8.42.1
- PHP version: 8.0.3

### Is your feature request related to a problem? Please describe
Product variants is one of the most important features when you are showing your product details. It would greatly help if we set up a default variant in order for it to be loaded when the product details loads for example. There are many advantages to creating this feature.

### Describe the solution you'd like
Maybe on the 'Create Variant' page you can set up a favorite/default on the icon-more-vertical.

### Why do you think this feature is something we should consider for Bazar?
This feature will allow designers which variant they want as default when the page loads.

**Comment by iamgergo** [comment]
Thanks!

Yes, this would be a nice addition. I think I will just use the same concept that we use for the user addresses.

<img width="418" alt="Képernyőfotó 2021-05-26 - 16 53 24" src="https://user-images.githubusercontent.com/6567179/119682468-33700e00-be43-11eb-8820-960a99061cf1.png">

This is what you meant?

How would you get the default variant? Something like this?

```php
// Easier

$product->getDefaultVariant();

// Nicer, but a bit more complex

$product->variants->default();
```

**Comment by ven7ura** [comment]
That's exactly what I meant.

As for how to get the default, you can keep using what your code style is currently.
