### ISSUE TITLE
Price is always null

### ISSUE THREAD

**Issue by richstandbrook** [conedevelopment/bazar#163]
- Bazar Version: dev-master
- Laravel Version: 8.44.0
- PHP Version: 7.4.19
- Database Driver & Version: PostgreSQL 12

### Description:
`Bazar\Models\Product::first()->price` results in `null` even though a price is set.
 

### Steps To Reproduce:
Create a product, enter a price, you can see from `domain.test/bazar/products` that no price is shown.

`Bazar\Models\Product::first()->price` and `Bazar\Models\Product::first()->formatedPrice` return `null`.

`Bazar\Models\Product::first()->prices` returns a `Bazar\Casts\Prices` object that shows the entered value under `storage->GBP->default`

**Comment by iamgergo** [comment]
Thanks!

Normally I've fixed it in dev-master, maybe you need to resave your price values.

The currencies should be lowercase `storage->GBP->default` --> `storage->gbp->default`.

**Comment by iamgergo** [comment]
I release v0.9.0, that should solve this now as a tagged version.

It contains a lots of BC-s, so you might update your code.
I'll update the documentation soon.

Thanks!
