### ISSUE TITLE
Create product missing price section

### ISSUE THREAD

**Issue by richstandbrook** [conedevelopment/bazar#164]
- Bazar Version: 0.9.0
- Laravel Version: 8.44.0
- PHP Version: 7.4.19
- Database Driver & Version: PostgreSQL 12

### Description:

As per #163 the price is now shown and accessible via `Bazar\Models\Product::first()->price` however I'm no longer able to edit it the Admin UI no longer shows the price configuration section and give this javascript error.

`TypeError: undefined is not an object (evaluating 'i.data.prices[n].default') — `

### Steps To Reproduce:

Install Baza

```bash
composer require conedevelopment/bazar
artisan bazar:install
artisan bazar:publish
```

Visit `http://domain.test/bazar/products/create` price section is missing and console shows error as above.

**Comment by iamgergo** [comment]
I don't experience this with a fresh installation of Bazar.

For me it works as is should and the prices block is shown as well.

Maybe with this code:

```
php artisan migrate:fresh

php artisan bazar:install --seed

php artisan bazar:publish --force
```

**Comment by richstandbrook** [comment]
Cool, I'm not seeing this anymore 👍
