### ISSUE TITLE
Product price validation error when 2 digits are submitted

### ISSUE THREAD

**Issue by ven7ura** [conedevelopment/bazar#165]
- Bazar Version: 0.9.0
- Laravel Version: 8.49.0
- PHP Version: 8.0.2

### Description:
When creating a product. The price only accepts 1 digit.
![image](https://user-images.githubusercontent.com/2340291/120112983-96102500-c135-11eb-8fd1-2bc890d1ab0d.png)

### Steps To Reproduce:
On the creation product page, input on the price 19.99 an error occurs on validation
'Please select a valid value...'

**Comment by iamgergo** [comment]
Fixed in https://github.com/conedevelopment/bazar/commit/5d3c8b20cfbeb0907dfe198326259c5b2196b809
