### ISSUE TITLE
Support for different vendors?

### ISSUE THREAD

**Issue by LarryBarker** [conedevelopment/bazar#170]
### Is your feature request related to a problem? Please describe

Hello, apologies if this isn't the correct format for this question. Is there a way to setup different vendors for products? 

We sell many varieties of the same product from different vendors and 

### Describe the solution you'd like

A simple relationship between product and vendor would be great. 

### Why do you think this feature is something we should consider for Bazar?

Allows for some flexibility and organization of products.

### Additional context

I thought about using a product property, but realized these are not saved and need to be recreated for each product. Perhaps if these were shared between products this feature would work?

**Comment by iamgergo** [comment]
Hello @LarryBarker,

Thanks for the issue. Could you provide a real life example please?
Just to make it sure, I understand well :)

Thanks!

**Comment by LarryBarker** [comment]
Thanks for your reply. Here's our use case:

We sell "Widgets". A "Widget" has a number of properties, such as width, height, length, doors, windows, etc.

"Widgets" are made by a number of manufacturers/vendors. 

Regardless of who manufactures or sells us the "Widget," the properties are the same. 

Hopefully this helps! Thanks!

**Comment by LarryBarker** [comment]
@iamgergo I know you're busy reorganizing, curious if you have any thoughts on this? I'd love to use the package to get our MVP ready.

**Comment by LarryBarker** [comment]
@iamgergo Thanks for your reply on my other issue. Hoping you might have some feedback here as well?

**Comment by iamgergo** [comment]
I'm really sorry for the very slow answer here.

So, if I understand well, you need a product schema? And when you are creating a new product, you want to select a schema and it would fill its properties, right?

**Comment by LarryBarker** [comment]
@iamgergo No worries, this is open source after all. 

Yes this is the basic idea. We only sell one type of product, just many variations of it (different lengths, widths, color, etc.) Depending on the Vendor, certain sizes, colors, etc. are available.

I'm hoping to avoid having to manage thousands of variants of the same product. One other challenge is that depending on the specific property selection, the price changes. 

I'm beginning to wonder if Bazar can even handle these use cases as is?
