### ISSUE TITLE
Declaration of Illuminate\Database\Eloquent\Factories\HasFactory::newFactory() must be compatible with Bazar\Models\User::newFactory(): ?Bazar\Database\Factories\UserFactory 

### ISSUE THREAD

**Issue by larsbo** [conedevelopment/bazar#172]
- Bazar Version: 0.9.1
- Laravel Version: 8.53.1
- PHP Version: 7.4.22
- Database Driver & Version: mysql 14.14

### Description:

During registration the following error occures:
`Declaration of Illuminate\Database\Eloquent\Factories\HasFactory::newFactory() must be compatible with Bazar\Models\User::newFactory(): ?Bazar\Database\Factories\UserFactory`

### Steps To Reproduce:
- fresh laravel installation
- [install laravel/breeze](https://laravel.com/docs/8.x/starter-kits#laravel-breeze)
- [install conedevelopment/bazar](https://bazar.conedevelopment.com/docs/installation#running-the-install-command)
- [extending the default user model](https://bazar.conedevelopment.com/docs/installation#extending-the-user-model) 
- [defining admins](https://bazar.conedevelopment.com/docs/admin#defining-admins)
- register a new user

**Comment by mwamodo** [comment]
Got the same error but realized that Bazar'Models\User uses hasFactory too. Just remove 'hasFactory' from your projects User Model.

**Comment by larsbo** [comment]
Works fine after removing the `HasFactory` trait from User model, thx @mwamodo !
