### ISSUE TITLE
Is present the list of work in progress for future? for Help develop?

### ISSUE THREAD

**Issue by ILDaviz** [conedevelopment/bazar#176]
Discord group or slack tks

**Comment by iamgergo** [comment]
Hey!

Thanks for the issue.

Yes, we are willing to continue working on Bazar.

However we are decided to create an ecosystem that we (and other developers) can use for different type of projects, and not only an ecommerce project.

This is what we are working on at the moment: https://github.com/conedevelopment/bazar/issues/177

Thanks for your patience!

**Comment by ILDaviz** [comment]
@iamgergo So were you thinking of abandoning the e-commerce side of this project? I would be interested to help on this side of project.

**Comment by iamgergo** [comment]
@ILDaviz No, not at all. The thing is after a few projects we were realizing, that Bazar would be more powerful if we would have a standalone CMS/Admin package and Bazar would extend its functionality as an e-commerce package. For example WordPress and WooCommerce.

So we are working on the base package (called Root), but we are going to keep Bazar and all its e-commerce stuff.

**Comment by ILDaviz** [comment]
@iamgergo Okay! I would be interested in helping, though.
In detail, I am interested in the e'commerce side or even in the root if needed. It can have great possibilities and I was thinking to add the parts that for me are missing in the core such as: reviews, manufacturers, meta, multilingual management etc..
