### ISSUE TITLE
Reorganizing Bazar

### ISSUE THREAD

**Issue by iamgergo** [conedevelopment/bazar#177]
Hello,

Currently we are reorganizing Bazar. 

We are about to create a small ecosystem that can be a great foundation for packages like Bazar.

That means, we are started to develop an admin framework (the concept is a bit like Laravel Nova) and a standalone UI framework and UI kit as well.

Right now we are focusing on the base framework but still Bazar 1.0.0 is coming in a bit reorganized way.

Hopefully we can give more details and share the code as a draft-release at Q4.

Thanks for your patience!

**Comment by f4llenz** [comment]
Hi,

Will there be many breaking changes in 1.0? I ask because I'd like to use this package, should I wait for 1.0 or is it fine to start using 0.9 right now? 

Thank you!

**Comment by iamgergo** [comment]
Hi,

Well, there will be mostly breaking changes. So, I'd suggest if you can wait a bit more, then you should wait for the 1.0.

Thanks!

**Comment by f4llenz** [comment]
Thank you for the hard work. Do you think 1.0 beta/draft could still be release this year?

**Comment by dgillier** [comment]
Any update on this ?

Thanks :)

**Comment by dcbndev** [comment]
@iamgergo will you release v1.0 this month or later on? I have a project that I want to build on bazar 1, but want to wait for the release.
Thank you

**Comment by iamgergo** [comment]
The base/foundation package is almost ready (for early beta) and its bazar integration as well.

It this month it won't be ready, but hopefully next month we can open the repo.

Sorry for the big delay, with all our other jobs it's not very easy to make that progress we planned. Thanks for your patience!

**Comment by iamgergo** [comment]
Hello everyone!

We published our foundation package, called Root: https://github.com/conedevelopment/root

The next steps will be finishing and publishing the documentation and migrating Bazar for this concept (in progress).

Thanks for your patience!
