### ISSUE TITLE
Cannot access product media

### ISSUE THREAD

**Issue by LarryBarker** [conedevelopment/bazar#179]
- Bazar Version: 0.8.2
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:

After attaching media to my product, I was first able to display in my view. After refreshing the page, I am now seeing an error:
```Call to a member function url() on null```

Not sure why this is happening or what changed between refreshes?

**Comment by LarryBarker** [comment]
Whoops.. I know what the issue is. I created a custom `Product` model to change the route model binding key to the product `slug`. Are the traits not inherited?

**Comment by iamgergo** [comment]
Hello!

I think the problem is, the new Product class is not bound into the container.

Here is the documentation: https://bazar.conedevelopment.com/docs/contracts-container-and-proxies#overriding-container-bindings

Let me know if this solves the problem! Thanks!
