### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by LarryBarker** [conedevelopment/bazar#180]
What icon library is used for admin and is there a list of available icons?

**Comment by ILDaviz** [comment]
I don't think they use any library, you can find the icons here https://github.com/conedevelopment/bazar/blob/master/resources/views/svg-icons.blade.php

**Comment by adamlaki** [comment]
Hey @LarryBarker,

As @ILDaviz says, there isn't an entire icon library pulled in. We use a small subset (at David's link) which you can extend. Unfortunately, right now, there isn't an easy showcase of the present ones...

These all are material icons (but you can anything just position it into a 24x24px base) as it comes, so if you download any from here: https://fonts.google.com/icons?selected=Material+Icons, you can add new ones. Download the SVG file, open in your IDE, copy it into the linked file (second link below) in the following format (and give it a unique ID):

```
<symbol id="your-custom-icon-name" viewBox="0 0 24 24">
     <path d="M16 6l2.29 2.29-4.88 4.88-4-4L2 16.59 3.41 18l6-6 4 4 6.3-6.29L22 12V6z"/>
</symbol>
```
For more information on Bazar's side, please check these two links:
- https://github.com/conedevelopment/bazar/blob/master/src/Repositories/AssetRepository.php#L79
- https://bazar.conedevelopment.com/docs/admin#custom-assets
