### ISSUE TITLE
Help Getting started?

### ISSUE THREAD

**Issue by drophit** [conedevelopment/bazar#190]
- Bazar Version: Latest
- Laravel Version: latest
- PHP Version: 8.1
- Database Driver & Version: mysql

### Description:
Help to setup - i have the vanilla install of Laravel 9 in Sail 8.1 docker container on windows. Is there a guide for running this in docker on windows? I also tried on my webserver (apache php7.4) and hit errors - is there anyway to pull this into a vanilla app running laravel sail?

**Comment by iamgergo** [comment]
Hello!

What is the actual error you want to solve?

Can you send the error you got when installing bazar?

**Comment by drophit** [comment]
Problem 1
    - Root composer.json requires conedevelopment/bazar ^0.9.1 -> satisfiable by conedevelopment/bazar[v0.9.1].
    - conedevelopment/bazar v0.9.1 requires laravel/framework ^8.43 -> found laravel/framework[v8.43.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).

**Comment by drophit** [comment]
OK i re-installed laravel 8 - now i need to know how to get to the dashboard - i am unsng admin@bazar.test buts what the password after installing breeze?

**Comment by iamgergo** [comment]
The password is `secret`.
