### ISSUE TITLE
Using constants

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/bazar#22]
May I send a PR with the following?

- Carbon constants (7 -> Carbon::DAYS_PER_WEEK)
- HTTP status codes (403 -> JsonResponse::HTTP_FORBIDDEN)
- and `$request->input('per_page', 25)` -> Controller::DEFAULT_ITEMS_PER_PAGE = 25

```
phpmnd --non-zero-exit-on-violation --include-numeric-string --extensions all src/
```

**Comment by iamgergo** [comment]
https://github.com/conedevelopment/bazar/commit/f0670b11e2736b04a51b5341f5dc7c4c92771f64
