### ISSUE TITLE
USER MODEL DOES NOT EXIST

### ISSUE THREAD

**Issue by eskayamadeus** [conedevelopment/bazar#233]
- Bazar Version: 1.1.2
- Laravel Version: 11.30.0
- PHP Version: 8.3.12
- Database Driver & Version: mysql8

### Description:

According to the docs, we are to extend `Bazar\Models\User` but that model really does not exist in the Bazar source code. It was deleted in the ["Rework" commit](https://github.com/conedevelopment/bazar/blob/46daa4d0b928cca0429469c0b9df718ebf4f988e/src/Models/User.php). 

I want to setup the code so what do I do?

**Comment by iamgergo** [comment]
Hey!

Yeah, the docs are outdated, we are working on releasing the new, refreshed docs!

Bazar now is an extension for our [Root admin](https://github.com/conedevelopment/root) package.

The docs are not yet published, but you can find the content already here: https://github.com/conedevelopment/root-docs

About Bazar: https://github.com/conedevelopment/root-docs/blob/master/bazar.md

Thanks!

**Comment by eskayamadeus** [comment]
Thank you!

**Comment by eskayamadeus** [comment]
If you need some help writing the documentation, let me know. I would love to help.
