### ISSUE TITLE
Colliding namespaces

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/bazar#34]
# 🚨 

https://github.com/conedevelopment/bazar/blob/d4ed847e8112b92b19c5ff2f578f62c8c87d227a/src/BazarServiceProvider.php#L174-L176

```php
        Blade::components([
// We have an import named "View": use Illuminate\Support\Facades\View;
            View\Components\Breadcrumbs::class,
        ]);
```

Suggestion: use only FQCN.

**Comment by szepeviktor** [comment]
How has this slipped under the radar of unit tests?? 📡

**Comment by iamgergo** [comment]
What's wrong with this?

**Comment by szepeviktor** [comment]
`use Illuminate\Support\Facades\View;` plus `View\Components\Breadcrumbs::class` equals non-existent `Illuminate\Support\Facades\View\Components\Breadcrumbs`
