### ISSUE TITLE
Not  a drop-in solution

### ISSUE THREAD

**Issue by plakhin** [conedevelopment/bazar#42]
I'm already using `spatie/laravel-medialibrary` and also already have `products` table.
So, I can't even install bazar :(

Currently, I'm renaming my tables, will see what issues I'll face next.

But I already see what needs to be changed:
1. Put table names in config.
2. Use `stubs` for migrations and publish them to application migrations directory, same like `larave/ui` does.

**Comment by iamgergo** [comment]
Hi! Thanks for the feedback!

> I'm already using spatie/laravel-medialibrary and also already have products table.

~~You mean `media` table?~~ Nothing, I misread.

Yes, you are right, table names should be different / configurable. However I might prefix them instead of put the names in config.

I'll take a look at what should be the best solution here.

Thanks!

**Comment by plakhin** [comment]
> You mean media table? 

I'm using `spatie/laravel-medialibrary`, so - yes, I have `media` table already.

I still didn't check, but looks like your solution for media is very similar to `spatie/laravel-medialibrary`.
As you consider Bazar as a drop-in solution, it might be a good idea to allow use of `spatie/laravel-medialibrary` instead of built-in media manager.

> Yes, you are right, table names should be different / configurable. However I might prefix them instead of put the names in config.

Prefixes is a good idea also!

**Comment by iamgergo** [comment]
So, not using the `spatie/laravel-medialibrary` was an intentional choice from our side. Spatie's package is really cool – we also use it in some projects – however, we wanted reusable media models, that can be attached to any other (or none) model and not only one. Our media manager has quite some differences – no dependencies, but the conversions are not as strong and wide as the medialib, so up and downsides as well –, but yes it works similary. For now, we are not considering to change.

I published the `0.2.2` tag which contains the prefixed table names.

Thanks!

**Comment by plakhin** [comment]
I'll take a look on how to migrate from spatie/laravel-medialibrary to the built-in solution, I'm not using much features and don't want 2 similar but different libraries in the project.

Thanks for really quick esponses and solutions!

**Comment by iamgergo** [comment]
Okay, good luck! If you managed to do that, could you share your experiences? It might be a good idea to write a how-to artice about this in the docs, because I think this can come up for others as well in the future.

Thank you!

**Comment by plakhin** [comment]
Sure! If I'll do, I share. Actually, I was looking for the solution like
Bazar for a while. I have some other urgent things to do for the project,
so this will take some time to take a look at Bazar and find out if it
suits, but seems like it is. However, I'm sure there will be some issues.
If you drop me a message to plakhin@gmail.com I'll send you my detailed
thoughts on what can be improved and may be I can help by making PRs in
case my vision similar to what you have.

**Comment by iamgergo** [comment]
Sure, no rush! We are expecting many issues related to Bazar, so if you find any feel free to open an issue. Thanks!

**Comment by plakhin** [comment]
One more thing:
1. User will got error running migrations if he already has `deleted_at` column in `users` table. 
2. On rolling migrations back, `deleted_at` column is being deleted regardless of being there before running bazar migrations.

I think this migration should be ignored if user already has `deleted_at` . One way is not to run migrations from package dir, but publish to application migrations dir instead, this way this migration can be not published if user already has `deleted_at` column in `users` table.

**Comment by iamgergo** [comment]
Good catch. I totally forgot about that scenario. Soon will fix that!

Thanks!

**Comment by iamgergo** [comment]
So, I've fixed the `deleted_at` migration, it does not create the column if it already exists.

However, the rollback part is tricky. For now, I just removed the `deleted_at` column drop until we find a solid solution.

Thanks for the idea and the feedback!

**Comment by plakhin** [comment]
> However, the rollback part is tricky. For now, I just removed the `deleted_at` column drop until we find a solid solution.

Yes, that part can be tricky. That's why my idea was not to publish and run the migration at all if soft deletes are being used already.

However, omitting the rollback part is a better solution then dropping the column, so users won't lose their data.
