### ISSUE TITLE
Integrate with existing products and categories

### ISSUE THREAD

**Issue by plakhin** [conedevelopment/bazar#44]
I have an existing project where Products and Categories are implemented already and being synced with warehouse management system and several external marketplaces. Products and Categories are simply Eloquent models. Also I have Characteristics model which belongs to Category and in many to many relationship with Product.
However, I want to implement Cart, Checkout, Discounts, Shipping and Taxes. 
Also, having an option to edit Product Characteristics would also be nice.

What is the easiest way to implement this? 
What will be the right way, considering Products have much more attributes than Bazar offers.

**Comment by szepeviktor** [comment]
Do you mean Product Attributes?

**Comment by plakhin** [comment]
> Do you mean Product Attributes?

The most important part of the uestion is how to use Products and Categories that already exists in a project.

Is there a way to use Cart, Checkout,  Shipping etc from Bazar with Products and Categories not from Bazar?

**Comment by iamgergo** [comment]
This is a good question. The thing is, Bazar is really at its beginning, so we might need more user input before creating a well-working migration guide from other frameworks / packages / custom apps.

I was thinking about creating a column called `custom_attributes` that can be easily used for this kind of migration, but for now, I'll wait for more input.

Until you can use the characteristics model and define a [dynamic relationship](https://laravel.com/docs/8.x/eloquent-relationships#dynamic-relationships) between the product/variation and the Characteristic model.

But let's keep this issue open for now until we'll receive more user feedback.

Thanks!

**Comment by plakhin** [comment]
Thanks for response!

Is there an easy way to use my own `Product` and `Category` implementation!?

I.e. I wan to extend my `App\Models\Product` class from `App\Models\Product` class, add/override some methods and make Bazar use my `App\Models\Product` instead of `Bazar\Models\Product`

UPD: For example, in `spatie/laravel-medialibrary` this is easy achievable by setting `model` in package config.

**Comment by iamgergo** [comment]
I think that it might be a better idea do bind the models/contracts to the container (like the `Bazar\Models\User`).

I was considering to do that a bit later, but since it already came up at this early stage, I'll work on this soon. I think it's better to use the container than using the config.

I'll ping you! Not promising in the next few days, but hopefully soon enought.

Thanks!

**Comment by plakhin** [comment]
Container can also be a solution, yes.
Will be waiting, thanks!

**Comment by iamgergo** [comment]
So, I added replaceable / proxyable bindings to the container. I'll update the docs about that, where I'll provide some examples of how to do that.

But from this point, you can rebind any model you wish of the given contract, so you can implement easily your own stuff. I'll let you know when the docs are ready.

**Comment by iamgergo** [comment]
So, I documented these here: https://bazar.conedevelopment.com/docs/core-concepts#contracts-container--proxies.
