### ISSUE TITLE
BUG: access to admin UI for all users!

### ISSUE THREAD

**Issue by plakhin** [conedevelopment/bazar#47]
Any authorized user is getting access to admin UI regardless of the presence of his email in `admins` list in config.

**Comment by plakhin** [comment]
Just found out that this is true for local environment, set in https://github.com/conedevelopment/bazar/blob/bcfc03451527883704a468ded144e034d8db0d23/src/BazarServiceProvider.php#L190
What's the purpose?

**Comment by iamgergo** [comment]
Well, we can remove the environment watcher. The purpose was to make development easier, but I think it's okay to remove it.

**Comment by iamgergo** [comment]
In the next release, it will be modified: https://github.com/conedevelopment/bazar/commit/61c149c7e5de5bde287e6bf891906c436e96b583

Until you can easily override the auth definition in your service provider.

Thanks!
