### ISSUE TITLE
Minor installation warning

### ISSUE THREAD

**Issue by eydun** [conedevelopment/bazar#86]
When running ``php artisan bazar:publish --tag=bazar-assets`` it gives:
![image](https://user-images.githubusercontent.com/12867/105986485-eb0f3200-6094-11eb-817c-158965f30508.png)

I am on Windows.

**Comment by iamgergo** [comment]
Hi!

Nice catch, soon I'll fix it!

Thanks!

**Comment by szepeviktor** [comment]
@iamgergo If you provide a list of exact CLI commands I can add them to CI.
I'm not sure how to check them...

**Comment by iamgergo** [comment]
@eydun I just tagged the `v0.4.2`, and this issue has been fixed.

Thanks!
