### ISSUE TITLE
Error installation with windows when using seed

### ISSUE THREAD

**Issue by vtscode** [conedevelopment/bazar#88]
Error Medium model when install

![image](https://user-images.githubusercontent.com/56695534/106199746-895fdc80-61e8-11eb-8a6a-a2e993861e6e.png)

**Comment by iamgergo** [comment]
Hi!

We don't experience this problem, nor the tests are having this issue.
Could you give the details of your system and which Laravel / PHP versions you have?

Thanks!

**Comment by iamgergo** [comment]
@vtscode Could you install a fresh Laravel and Bazar and repeat the installation process?

Do you still get this error?

Thanks!

**Comment by eydun** [comment]
I am also on Windows, and I do not experience any problems when migrating with seed.

**Comment by szepeviktor** [comment]
Meanwhile CI checks that for us.
https://github.com/conedevelopment/bazar/actions/runs/563423582
