### ISSUE TITLE
Should change current project package.json

### ISSUE THREAD

**Issue by curder** [conedevelopment/bazar#90]
In this section: [customizing the ui](https://bazar.conedevelopment.com/docs/admin#customizing-the-ui) We should change our `package.json` file from `vendor/conedevelopment/bazar/package.json`

```
"devDependencies": {
    "@inertiajs/inertia": "^0.3.6",
    "@inertiajs/inertia-vue": "^0.2.4",
    "axios": "^0.21.0",
    "bootstrap": "^4.5.3",
    "chart.js": "^2.9.4",
    "cross-env": "^7.0.3",
    "laravel-mix": "^5.0.7",
    "quill": "^1.3.7",
    "resolve-url-loader": "^3.1.2",
    "sass": "^1.32.4",
    "sass-loader": "^8.0.0",
    "simplebar": "^5.3.0",
    "vue": "^2.6.12",
    "vue-loader": "^15.9.5",
    "vue-template-compiler": "^2.6.12"
}
```

**Comment by iamgergo** [comment]
Do you think, in the case of publishing assets, a command like this https://github.com/laravel/ui/blob/3.x/src/Presets/Preset.php#L23-L50, would be a help of pulling in dependencies automatically?

**Comment by curder** [comment]
> Do you think, in the case of publishing assets, a command like this https://github.com/laravel/ui/blob/3.x/src/Presets/Preset.php#L23-L50, would be a help of pulling in dependencies automatically?

Maybe it's a good try, but I wonder why not compress and package the Vue, JS and CSS code? And directly reference in the app.blade.php template?

**Comment by iamgergo** [comment]
I'm not sure if I understand you. We do what you just described.

**Comment by iamgergo** [comment]
With `v0.4.3` we added the `--packages` and the `--mix` flags to the `bazar:publish` command, which updates the packages.json and the mix file. So, update publishing your assets all you need to do is just run `npm install && npm run dev`.
